### PR TITLE
connect hook to register

### PR DESCRIPTION
**Pull request by Antipkin-A**
Changed method for connect hook

### CODE REVIEW

**Review by eneiluj — APPROVED** [review]
I confirm it solves the sync issue on NC 21 and 22. Hooks are now actually triggered and documents are downloaded again if some file changes were pushed from a client.

It does not affect NC 23 for which it was already working fine.

**Review by juliushaertl — APPROVED** [review]
Also makes sense from a conceptual perspective in how the register and boot methods are caleld during Nextcloud application bootstrap.

**Comment by djtilo-ol** [comment]
> 
"eneiluj"
It does not affect NC 23 for which it was already working fine.
> 
I installed a fresh NextCloud 23 on my webspace and am sorry to say that the identical issue as in NC22 remains. Synced updates to documents (Office & PDF) are not recognized and an older version is shown.
The plugin is version 7.2.1 & I downloaded the latest NC 23.0.0, OO 6.4.2.
Regards

**Comment by eneiluj** [comment]
@djtilo-ol Thanks for the feedback. Have you tried to apply this patch to check if it actually fixes the issue in NC 23?

**Comment by djtilo-ol** [comment]
Hi, I can do that, sure. I am an ambitious rookie, but I can't quite make out what I have to alter in the file application.php as mentioned [here](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/562#issuecomment-982553965)
Can I download a patched file somewhere?

**Comment by eneiluj** [comment]
You can see the diff in the [Files changed](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/pull/566/files) tab right here.
Or here is a link to the raw file from this branch: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/raw/6bcbce371dcd1ebad02ce68b2454fd6346a046ce/appinfo/application.php

**Comment by djtilo-ol** [comment]
This fixes the issue in NC22 and NC23 - outstanding & thank you
nc22 file sync
nc23 file sync
!

**Comment by eneiluj** [comment]
@djtilo-ol And thank you for the feedback!

**Comment by djtilo-ol** [comment]
:) With your help I was able to send the patched file to our NC provider who added it for us, so that the problem is resolved until the new connector is released - that is absolutely amazing! Merry Christmas, should you celebrate it.

**Comment by biva** [comment]
It works for me as well :)

**Comment by flyingdgithub** [comment]
Could someone please explain how to patch Nextcloud-VM with ONLYOFFICE integrated. I can't find anything resembling the 'application.php' file.

**Comment by djtilo-ol** [comment]
Hi, in the NextCloud folder you find the application.php in 
/apps/onlyoffice/appinfo
Regards

**Comment by flyingdgithub** [comment]
Thanks, I had to discover how find the content off /var/www 
Unfortunately still big issues,  office files won't sync back to windws pc with nextcloud app, reverted to 3.36 even, still not. I reverted this ' fix' again and no w seens better, so weird

**Comment by djtilo-ol** [comment]
The issue discussed here was that OnlyOffice could not open the latest version once two or three alterations were made locally and synced to NextCloud.
I checked by comparing Hashes of the files, like a fingerprint if you want.
Checksum is an app for NextCloud which allows you to generate i.e. MD5 hash value, then compare to local file and so on. This way I detected that NC was doing its job properly and OO was having a hard time opening the latest version.

**Comment by flyingdgithub** [comment]
There is some voodoo processing going on to make up for the lack of an an actual process to deal with these document updates. See also: https://github.com/nextcloud/documentserver_community/issues/191#  I had to manually add a cron  job to get some sort of reliable behavior, unbelievable really.

**Comment by flyingdgithub** [comment]
Not to mention there is another bug about onlyoffice just stalling for merely trying to check the previous versions.

**Pull request merged**
