### PR TITLE
Exposed leeway setting in the JWT library

### PR DESCRIPTION
**Pull request by anon8675309**
If the system clock of the document server is even a second slower than the nextcloud server, the JWT token will be rejected as being "not yet valid". This can be seen in the logs (Nextcloud -> Settings -> Administration -> Logging).

The error message shown to the user when this happens is more generic:

"Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)"

This error message has been reported on the bug tracker several times, but it is not clear when the connection failure was due to imperfectly synchronized clocks and when it was due to network connectivity, DNS issues, the JWT not being sent, the secret being wrong, or some other issue.

Here are the tickets that may be fixed by this:
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/345 https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/548 https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/315 https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/290 https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/127

There's also one on the owncloud fork that may be fixed by this as well: https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/278

### CODE REVIEW

**Comment by anon8675309** [comment]
Is there anything I can do to help get this merged into the default branch?

**Comment by anon8675309** [comment]
I've pulled in the changes from the default branch so this can be merged cleanly

**Comment by anon8675309** [comment]
@LinneyS is this change something that can be upstreamed into the official repo?

**Comment by anon8675309** [comment]
In case the onlyoffice-nextcloud app is still maintained, please accept this merge request.

However, since it's been several months and this pull request hasn't been merged or commented on, I have to conclude that onlyoffic-nextcloud is now unmaintained. This will be my last follow up unless I get a notification about activity from github.com.

**Comment by LinneyS** [comment]
Thank you very much for your suggestion
We will review these changes and try to implement them in the next release.

**Comment by LinneyS** [comment]
It was decided not to move the parameter to the admin settings page yet. Enough in the server configuration file.

**Comment by anon8675309** [comment]
How can the leeway value be set without the configuration option being exposed in the admin settings page?  Is the only option to do direct SQL UPDATE statements on the production server?

**Comment by LinneyS** [comment]
You can set it in `config/config.php`
```
'onlyoffice' => array (
    'jwt_leeway' => 10
)
```

**Pull request merged**
